apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
    chart: prometheus-11.12.1
    component: server
    heritage: Helm
    release: prometheus
  name: prometheus-nginx
  namespace: prometheus
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
    component: server
    release: prometheus
  type: ClusterIP