apiVersion: v1
kind: Service
metadata:
  name: nginx-service-nlb-ip
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
spec:
  ports:
    - port: 28080
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app: nginx